---
title: "combine_canum_files"
author: "Kirsten Birch Håkansson, DTU Aqua"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

library(readxl)
library(dplyr)
library(ggplot2)

options(scipen = 999)

path_boot <- "../boot/data/historical_data/sc_sheets_old_format/"
path_data <- "../data/"
```

# 27.3.a
## historical data 2000-2015
```{r, include = F}
dat_old <- read.csv(paste0(path_data, "canum_old_format_3a.csv") ,sep = ";")
unique(dat_old$year)
unique(dat_old$ctry)


head <- distinct(dat_old, ctry, year, quarter, fleet, area, catch_t)
wr <- distinct(subset(dat_old, !is.na(wr)), wr)
full_wr <- cross_join(head, wr)

dat_old_full_wr <- left_join(full_wr, dat_old)
dat_old_full_wr$canum_1000[is.na(dat_old_full_wr$canum_1000)] <- 0

dat_old <- dat_old_full_wr

```


## files from recent years 2016-2024

```{r, include = F}
dat_16 <- read.csv(paste0("../boot/data/data_from_recent_years/1_canum_2016.csv"))

years <- c(2017:2024)
dat_new <- c()

for (i in years) {
  
  dat_0 <- read.csv(paste0("../boot/data/data_from_recent_years/C1_her2024_canum_without_imputations_", i, ".csv"))
  dat_0 <- subset(dat_0, year == i)
  dat_new <- bind_rows(dat_new, dat_0)
  
}
unique(dat_new$year)
unique(dat_new$ctry)

dat_new <- bind_rows(dat_16, dat_new)
```

## Swedish update

```{r, include = F}

swe <- read.csv(
  "../boot/data/updated_data_from_sweden/WBSS_DEWK_SWE_2000_2024_IC_20-24_final.csv",
  header = F,
  sep = ",", colClasses="character", fill=T, col.names = paste0("V",seq_len(33))
)


hi <- subset(swe, swe$V1 == "HI")[, c(1:12)]
colnames(hi) <- c(
  "recordType",
  "country",
  "year",
  "seasonType",
  "season",
  "fleet",
  "areaType",
  "fisghingArea",
  "depthRange",
  "unitEffort",
  "effort",
  "areaQualifier"
)

si <- subset(swe, swe$V1 == "SI")[, c(1:24)]
colnames(si) <- c(
  "recordType",
  "ctry",
  "year",
  "seasonType",
  "quarter",
  "subFleet",
  "areaType",
  "area",
  "depthRange",
  "sppName",
  "stock",
  "catchCategory",
  "reportingCategory",
  "dataToForm",
  "usage",
  "samplesOrigin",
  "qualityFlag",
  "unitCaton",
  "catch_t",
  "offLandings",
  "varCaton",
  "infoFleet",
  "infoStockCoordinator",
  "infoGeneral"
)

unique(si$unitCaton)
si$catch_t[is.na(si$catch_t)] <- si$offLandings[is.na(si$catch_t)]

si <- select(si, -recordType, -seasonType, -areaType, -depthRange, -stock,
             -catchCategory, -reportingCategory, -dataToForm, -usage, -samplesOrigin, 
             -qualityFlag, -unitCaton, -offLandings, -varCaton, -infoFleet, 
             -infoStockCoordinator, -infoGeneral)

sd <- subset(swe, swe$V1 == "SD")[, c(1:33)]
colnames(sd) <- c(
  "recordType",
  "ctry",
  "year",
  "seasonType",
  "quarter",
  "subFleet",
  "areaType",
  "area",
  "depthRange",
  "sppName",
  "stock",
  "catchCategory",
  "reportingCategory",
  "sex",
  "canumType",
  "wr",
  "plusGroup",
  "sampledCatch",
  "noSample",
  "noLength",
  "numSamplesAge",
  "noAge",
  "unitMeanWeight",
  "unitCanum",
  "unitAgeOrLength",
  "unitMeanLength",
  "maturity",
  "numberCaught",
  "meanWeight",
  "meanLength",
  "varNumLanded",
  "varWgtLanded",
  "varLgtLanded"
)

sd <- select(sd, -recordType, -seasonType, -areaType, -depthRange, -stock,
             -catchCategory, -reportingCategory, -sex,
             -canumType, -plusGroup, -sampledCatch, -unitMeanWeight, -unitCanum, 
             -unitAgeOrLength, -unitMeanLength, -maturity, -numSamplesAge, 
             -varNumLanded, -varWgtLanded, -varLgtLanded)


test_wr <- subset(sd, wr == 9)
unique(test_wr$area)
sd <- subset(sd, wr != 9)


sisd <- left_join(si, sd)

sisd$ctry <- "Sweden"
sisd$canum_1000 <- as.numeric(sisd$numberCaught)/1000
sisd$weca_g <- as.numeric(sisd$meanWeight)*1000
sisd$year <- as.numeric(sisd$year)
sisd$quarter <- as.numeric(sisd$quarter)
sisd$catch_t <- as.numeric(sisd$catch_t)
sisd$wr[sisd$wr == "8"] <- "8+"
sisd$noSample <- as.numeric(sisd$noSample)
sisd$noLength <- as.numeric(sisd$noLength)
sisd$noAge <- as.numeric(sisd$noAge)

head <- distinct(sisd, ctry, year, quarter, subFleet, area, sppName, catch_t)

wr <- distinct(subset(sisd, !is.na(wr)), wr)
full_wr <- cross_join(head, wr)

sisd_full_wr <- left_join(full_wr, sisd)
sisd_full_wr$numberCaught[is.na(sisd_full_wr$numberCaught)] <- 0


swe <- sisd_full_wr

swe <- subset(swe, area %in% c("27.3.a.20", "27.3.a.21", "27.3.b.23",
                               "27.3.c.22", "27.3.d.24"))

```

# Combine present time series
```{r, include = F}
dat_org <- bind_rows(dat_new, dat_old)
distinct(dat_org, ctry, area)

write.table(dat_org, "../data/C1_her2024_canum_without_imputations_present_time_series.csv", row.names = F, sep = ";")

```

# Update with Swedish data
```{r, include = F}

dat_org_m_swe <- subset(dat_org, ctry != "Sweden")

test <- bind_rows(dat_org_m_swe, swe)
test$canum_1000[!(is.na(test$imputation))] <- 0
test$weca_g[!(is.na(test$imputation))] <- NA

write.table(test, "../data/C1_her2024_canum_without_imputations_updated_swe.csv", row.names = F, sep = ";")



sop <- summarise(group_by(test, ctry, sppName, year, area, 
              quarter, fleet, subFleet, catch_t),
              sop = sum((canum_1000 * weca_g) / 1000, na.rm = T))


test_sop <- left_join(select(test, -sop), sop)
test_sop$sopCorr <- (test_sop$catch_t / test_sop$sop)

nrow(subset(test_sop, sopCorr != 1))

swe_org <- subset(dat_org, ctry == "Sweden")
swe_org_sum <- summarise(group_by(subset(swe_org, wr == "8+"), year, area), ton = sum(catch_t, na.rm = T))
swe_org_sum$type <- "present"
si$year <- as.numeric(si$year)
swe_new_sum <- summarise(group_by(si, year, area), ton = sum(as.numeric(catch_t), na.rm = T))
swe_new_sum$type <- "update"

swe_comb <- bind_rows(swe_org_sum, swe_new_sum)

```

```{r}

ggplot(data = swe_comb, aes(x = year, y = ton, col = type)) +
  geom_line() +
  facet_wrap(~area, scales = "free_y")
```

