---
title: "read_in"
author: "Kirsten Birch Håkansson, DTU Aqua"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)

library(readxl)
library(dplyr)

source("../utils/read_canum_sheet_old_format_IIIa.R")

path_in <- "../boot/data/historical_data/sc_sheets_old_format/"

```


# 2012
```{r}
file <- "HER-IIIa-2012.xls"

sheet_names <- excel_sheets(path = paste0(path_in, file))

SD20NO <- read_canum_sheet_old_format_IIIa(file = paste0(path_in, file), sheet_name = "SD20-NO") # No imputations
sum(unique(SD20NO$catch_t))

SD20SE <- read_canum_sheet_old_format_IIIa(file = paste0(path_in, file), sheet_name = "SD20-SE") # No imputations
sum(unique(SD20SE$catch_t))

SD20DK <- read_canum_sheet_old_format_IIIa(file = paste0(path_in, file), sheet_name = "SD20-DK")
sum(unique(SD20DK$catch_t))
SD20DK$imputation <- NA
SD20DK$imputation[SD20DK$quarter == 1 & SD20DK$fleet == "C"] <- "SWE_IIIaN_Q1"
SD20DK$imputation[SD20DK$quarter == 2 & SD20DK$fleet == "C"] <- "SWE_IIIaN_Q2"

SD20DE <- read_canum_sheet_old_format_IIIa(file = paste0(path_in, file), sheet_name = "SD20-OTH")
sum(unique(SD20DE$catch_t))
SD20DE$imputation <- NA
SD20DE$imputation[SD20DE$quarter == 3 & SD20DE$fleet == "C"] <- "DEN_IIIaN_Q3"
SD20DE$imputation[SD20DE$quarter == 4 & SD20DE$fleet == "C"] <- "DEN_IIIaN_Q4"

SD21SE <- read_canum_sheet_old_format_IIIa(file = paste0(path_in, file), sheet_name = "SD21-SE")
sum(unique(SD21SE$catch_t))
SD21SE$imputation <- NA
SD21SE$imputation[SD21SE$quarter == 2 & SD21SE$fleet == "C"] <- "SWE_IIIaS_Q1"
SD21SE$imputation[SD21SE$quarter == 3 & SD21SE$fleet == "C"] <- "SWE_IIIaN_Q3"
SD21SE$imputation[SD21SE$quarter == 4 & SD21SE$fleet == "C"] <- "SWE_IIIaN_Q4"

SD21DK <- read_canum_sheet_old_format_IIIa(file = paste0(path_in, file), sheet_name = "SD21-DK")
sum(unique(SD21DK$catch_t))
SD21DK$imputation <- NA
SD21DK$imputation[SD21DK$quarter == 1 & SD21DK$fleet == "C"] <- "SWE_IIIaS_Q1"
SD21DK$imputation[SD21DK$quarter == 2 & SD21DK$fleet == "C"] <- "SWE_IIIaS_Q1"

c12 <- bind_rows(SD20DE, SD20DK, SD20NO, SD20SE, SD21DK, SD21SE)

rm(SD20DE, SD20DK, SD20NO, SD20SE, SD21DK, SD21SE)

summarise(group_by(subset(c12, wr == "8+"), year, division), ton = sum(catch_t, na.rm = T))
```

